# Generated by Django 3.2.4 on 2021-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='defaultdays',
        ),
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.IntegerField(default=18, help_text='Requesting Leaves', verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('annual', 'Sick Leave'), ('circumstancial', 'Casual Leave')], default='annual', max_length=25, null=True),
        ),
    ]
