# Generated by Django 3.2.4 on 2021-07-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20210709_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('annual', 'Sick Leave'), ('circumstancial', 'Casual Leave'), ('Maternal Leave', 'Maternak Leave'), ('Marriage', 'Marriage')], default='annual', max_length=25, null=True),
        ),
    ]
