# Generated by Django 3.2.4 on 2021-07-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('annual', '\tAnnual Leave'), ('circumstancial', 'Circumstancial Leave'), ('Maternal Leave', 'Maternal Leave'), ('Marriage', 'Marriage Leave')], default='annual', max_length=25, null=True),
        ),
    ]
