# Generated by Django 3.2.4 on 2021-06-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210617_0708'),
        ('leave', '0002_alter_leave_leavetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='defaultdays',
        ),
        migrations.AddField(
            model_name='leave',
            name='total_leave',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('annual', 'Sick Leave'), ('circumstancial', 'Casual Leave')], default='annual', max_length=25, null=True),
        ),
    ]
