# Generated by Django 3.2.4 on 2021-06-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20210617_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='total_leave',
        ),
    ]
