# Generated by Django 3.2.4 on 2021-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_remove_leave_total_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='days',
            field=models.IntegerField(default=18, help_text='Requesting Leaves', verbose_name='Days'),
        ),
    ]
