# Generated by Django 3.2.4 on 2021-06-16 10:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200904_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dateissued',
        ),
        migrations.AddField(
            model_name='employee',
            name='total_leave',
            field=models.PositiveIntegerField(default=18, help_text='Total days off allowed', max_length=2, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(21)], verbose_name='Total Leave'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.role', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(help_text='date of employement', null=True, verbose_name='Employement Start Date'),
        ),
    ]
