# Generated by Django 3.2.4 on 2021-06-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210616_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], default='Not Known', max_length=15, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(help_text='date of employement', null=True, verbose_name='Employment Start Date'),
        ),
    ]
