# Generated by Django 3.2.4 on 2021-07-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_year', models.PositiveIntegerField(null=True, verbose_name='Days in this Year')),
                ('last_year', models.PositiveIntegerField(default=18, verbose_name='Days in present Year')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Year')),
            ],
        ),
    ]
