# Generated by Django 3.2.4 on 2021-07-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_year_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='total_leave',
        ),
        migrations.AlterField(
            model_name='year',
            name='last_year',
            field=models.PositiveIntegerField(default=18, verbose_name='Days in last Year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='present_year',
            field=models.PositiveIntegerField(default=18, null=True, verbose_name='Days in this Year'),
        ),
    ]
