# Generated by Django 3.2.4 on 2021-08-02 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leave_leavetype'),
        ('employee', '0008_auto_20210728_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeback', models.TextField(max_length=500, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.leave', verbose_name='Leave')),
            ],
        ),
    ]
