# Generated by Django 3.2.4 on 2021-08-08 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0012_auto_20210803_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(blank=True, default='AB125', max_length=10, null=True, verbose_name='Employee ID Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Fixed Term Contract', 'Fixed Term Contract'), ('Part-Time', 'Open Ende Contact'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer')], default='Fixed Term Contract', max_length=200, null=True, verbose_name='Employee Type'),
        ),
    ]
