# Generated by Django 3.2.4 on 2021-08-09 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0013_auto_20210808_1242'),
    ]

    operations = [
    ]
