# Generated by Django 3.2.4 on 2021-08-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_feedback_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
    ]
