# Generated by Django 3.2.4 on 2021-08-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_feedback_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='employee',
        ),
    ]
