# Generated by Django 3.2.4 on 2021-08-09 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0016_remove_feedback_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(default=66, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Employee'),
            preserve_default=False,
        ),
    ]
