# Generated by Django 3.2.4 on 2021-08-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_auto_20210809_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_year',
            field=models.PositiveIntegerField(blank=True, default=18, null=True, verbose_name='Days in last Year'),
        ),
        migrations.AddField(
            model_name='employee',
            name='present_year',
            field=models.PositiveIntegerField(blank=True, default=18, null=True, verbose_name='Days in this Year'),
        ),
    ]
