# Generated by Django 3.2.4 on 2021-08-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_auto_20210809_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Fixed Term Contract', 'Fixed Term Contract'), ('Open Ended Contract', 'Open Ended Contact'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer')], default='Fixed Term Contract', max_length=200, null=True, verbose_name='Employee Type'),
        ),
    ]
